### ISSUE TITLE
OperationTypeNode enum not compatible with graphql v15

### ISSUE THREAD

**Issue by SirReiva** [apollographql/federation#1481]
I´ve updated to the last release  of apollo gateway and federation with graphql v15
 and I get this error:

![image](https://user-images.githubusercontent.com/50754871/152548911-4761c1c4-ff76-4a3d-87bf-8bc9ec3973c9.png)
Apollo source code error stack line:
![image](https://user-images.githubusercontent.com/50754871/152551813-751796a5-5385-4a54-a5ab-2027c9b98b0c.png)

Dependencies:
![image](https://user-images.githubusercontent.com/50754871/152551077-b6280908-fd73-4f36-909d-36fcfe00544f.png)

I found that graphql v16 package exports enum "OperationTypeNode" but graphql v15 not export it

v15 screenshot:
![image](https://user-images.githubusercontent.com/50754871/152550580-720fe4e4-fa9b-46f1-ba31-43e65d6654ac.png)
v16 screenshot:
![image](https://user-images.githubusercontent.com/50754871/152550883-f63d05b9-f1bf-4b33-8bb8-ba3fcbb2d2e7.png)

**Comment by trevor-scheer** [comment]
Thanks for reporting, I should be able to take a look at this today. cc @IvanGoncharov @clenfest

**Comment by trevor-scheer** [comment]
I was able to investigate a bit this morning and found a handful of other v15/v16 incompatibilities that were introduced, but unfortunately haven't had the time to resolve them.

If anyone runs into this or other related compat issues with v15, for now the workaround is to either use `graphql@16` or a previous version of gateway. I'd be interested to hear if/why moving to v16 is not an option for anyone stuck on v15.

My hope is to continue supporting both, but depending on the changes required I might take it to the team to decide how important it is that we continue supporting v15 and possibly recommend dropping it. I'll provide updates on this issue.

**Comment by dchambers** [comment]
Thanks for looking into this @trevor-scheer 🙇 . I just this hit this myself, and in my case there were two TypeScript related problems:

1. The reference to the `ASTVisitFn` type within `composition/DirectiveMetadata.d.ts`.
2. The use of `Kind` as module type rather than an object type within `composition/utils.d.ts`.

As for not upgrading to `graphql@16`, I'll try to give this a go but it looks like a tough ask at the moment. Based on my current `yarn.lock` I have the following libraries which don't yet have v16 support even in their latest version:

- `@graphql-inspector/cli@^3.0.2`
- `@graphql-tools/batch-execute@^8.3.1`
- `apollo-graphql@^0.9.5`
- `apollo-server-integration-testing@^3.0.0`
- `apollo-utilities@1.3.4`
- `express-graphql@0.12.0`
- `graphql-sse@1.0.6`
- `graphql-ws@^5.4.1`

plus these libraries are upgradable, but require semver incompatible updates which may need some attention:

- `@graphql-tools/delegate@npm:^7.1.5`
- `@graphql-tools/load@npm:^6.2.8`
- `@graphql-tools/merge@npm:^6.2.12`
- `@graphql-tools/schema@npm:^7.1.5`
- `@graphql-tools/url-loader@npm:^6.10.1`
- `@graphql-tools/utils@npm:8.0.2`
- `@graphql-tools/wrap@npm:^7.0.4`

I'll let you know how I get on...

**Comment by trevor-scheer** [comment]
Thanks for the detailed breakdown @dchambers. We just released new versions of the federation 0.x packages which claim support for the range `"graphql": "^15.8.0 || ^16.0.0"`. The latest fix also includes an additional CI step to ensure we don't break this compatibility going forward. For anyone following along, thanks for your patience 🙇

**Comment by dchambers** [comment]
Hey @trevor-scheer 👋 . Just an an FYI that I just tried upgrading to the latest Apollo libs and I'm still seeing one of the two underlying issues I mentioned:

 > The use of `Kind` as module type rather than an object type within `composition/utils.d.ts`.

and in fact this has also been reported as #1538.

This problem occurs because `Kind` is an object in `graphql` version `15.8.0`, but an `enum` in `16.0.0`:

- https://github.com/graphql/graphql-js/commit/73025aa009039c1e2e74f7bbd088ec6ab6e07e94

> The latest fix also includes an additional CI step to ensure we don't break this compatibility going forward. For anyone following along, thanks for your patience 🙇

I guess because it's a type error that it's possible to run the tests without type checking and not see it. For me I see it when I try to run `tsc` on a program that includes `@apollo/gateway`, and this is what I see when I click on the error in the terminal:

![image](https://user-images.githubusercontent.com/283294/156855356-de47b619-3b3c-433d-b5a4-baa41ad6dd7e.png)

**Comment by trevor-scheer** [comment]
Hey @dchambers, thanks for the update. Type checking is happening during that CI step (it builds before testing) so something sounds off.

Can you share a reproduction either on codesandbox or github that I can pull down and take a look at? I suspect there's some kind of dependency issue, the `package.json` (and very possibly the `package-lock.json`) should be pretty telling.

**Comment by trevor-scheer** [comment]
@dchambers your issue should be resolved now via https://github.com/apollographql/federation/pull/1585. Let me know if you still see the problem in the latest v0 federation packages.

**Comment by dchambers** [comment]
Hi @trevor-scheer 👋 . Thanks so much for continuing to look into this issue! I just now tried upgrading all Apollo libs to the latest versions and the error messages are unchanged for me unfortunately.

Here's a fairly minimal reproduction so you can see for yourself:

- https://stackblitz.com/edit/node-7sp9dl?file=index.ts
